#ifndef __DAEMONS_H
#define __DAEMONS_H

#include <dirs.h>

#define ADVANCE_D            (DIR_SECURE_DAEMONS+"/advance")
#define ALCHEMIST_D          (DIR_DAEMONS+"/alchemist")
#define ASTRONOMY_D          (DIR_DAEMONS+"/astronomy")
#define BANISH_D             (DIR_DAEMONS+"/banish")
#define BANK_D               (DIR_SECURE_DAEMONS+"/bank")
#define BBOARD_D             (DIR_SECURE_DAEMONS+"/bboard")
#define CASTLE_D             (DIR_DAEMONS+"/castle")
#define CHAT_D               (DIR_DAEMONS+"/chat")
#define DSCHAT_D               (DIR_SECURE_DAEMONS+"/chat")
#define CMD_D                (DIR_DAEMONS+"/command")
#define ECONOMY_D            (DIR_DAEMONS+"/economy")
#define ESTATES_D            (DIR_DAEMONS+"/estates")
#define EVENTS_D             (DIR_SECURE_DAEMONS+"/events")
#define FINGER_D             (DIR_SECURE_DAEMONS+"/finger")
#define FOLDERS_D            (DIR_SECURE_DAEMONS+"/folders")
#define HELP_D               (DIR_DAEMONS+"/help")
#define INTERMUD_D           (DIR_DAEMONS+"/intermud")
#define SERVICES_D           (DIR_DAEMONS+"/services")
#define LANG_D               (DIR_DAEMONS+"/languages")
#define LETTERS_D            (DIR_SECURE_DAEMONS+"/letters")
#define LOCALPOST_D          (DIR_SECURE_DAEMONS+"/localpost")
#define MCP_D		     (DIR_SECURE_DAEMONS+"/mcp_d")
#define MULTI_D              (DIR_DAEMONS+"/multi")
#define NETWORK_D            (DIR_DAEMONS+"/network")
#define NEWS_D               (DIR_DAEMONS+"/news")
#define OPTIONS_D            (DIR_SECURE_DAEMONS+"/options")
#define PARTY_D              (DIR_DAEMONS+"/party")
#define PASSWD_D             (DIR_MORTAL_CMDS+"/_passwd")
#define PLAYER_D             (DIR_SECURE_DAEMONS+"/player")
#define POLITICS_D	     (DIR_SECURE_DAEMONS+"/politics")
#define PROJECT_D            (DIR_DAEMONS+"/project")
#define RACE_D               (DIR_DAEMONS+"/race")
#define REFS_D               (DIR_DAEMONS+"/refs")
#define REMOTEPOST_D         (DIR_SECURE_DAEMONS+"/remotepost")
#define SERVICES_D           (DIR_DAEMONS+"/services")
#define SHUT_D               (DIR_SECURE_DAEMONS+"/shutdown")
#define SKILLS_D             (DIR_DAEMONS+"/skills")
#define SOUL_D               (DIR_DAEMONS+"/soul")
#define TERMINAL_D           (DIR_DAEMONS+"/terminal")
#define TIME_D               (DIR_DAEMONS+"/timezones")
#define USERS_D              (DIR_SECURE_DAEMONS+"/users")
#define VIRTUAL_D            (DIR_DAEMONS+"/virtual")
#define VOTING_D             (DIR_DAEMONS+"/voting")

#endif /* __DAEMONS_H */
